// src/components/Tags.tsx
import React from "react";

function Tags({ tags }) {
  return (
    <div className="tags">
      {tags.map((tag, index) =>
        tag && tag.name ? (
          <React.Fragment key={index}>
            {tag.link ? (
              <a href={tag.link} target="_blank" rel="noopener noreferrer" className={`plantag ${tag.additionalClass}`}>
                {tag.name}
              </a>
            ) : (
              <span className={`plantag ${tag.additionalClass}`}>{tag.name}</span>
            )}
          </React.Fragment>
        ) : null
      )}
    </div>
  );
}

export default Tags;

// docs/.vitepress/theme/components/Tags.vue
<script setup lang="ts">
interface Tag {
  name: string
  link?: string
  additionalClass?: string
}

defineProps<{ tags: Tag[] }>()
</script>

<template>
  <div class="tags">
    <template v-for="(tag, index) in tags" :key="index">
      <a
        v-if="tag && tag.name && tag.link"
        :href="tag.link"
        target="_blank"
        rel="noopener noreferrer"
        :class="['plantag', tag.additionalClass]"
      >
        {{ tag.name }}
      </a>
      <span
        v-else-if="tag && tag.name"
        :class="['plantag', tag.additionalClass]"
      >
        {{ tag.name }}
      </span>
    </template>
  </div>
</template>
